### PR TITLE
Add .rdef file + update addresources.sh

### PR DESCRIPTION
**Pull request by BachToTheFuture**
Sorry! I accidentally deleted my fork, so please look at this PR instead :)

### CODE REVIEW

**Comment by bach5000** [comment]
@owenca Would I do something like this for the qmake file?
```
littlewriter_target.commands = rc -o Littlewriter.rsrc Littlewriter.rdef && xres -o LittleWriter Littlewriter.rsrc && mimeset -f LittleWriter

QMAKE_EXTRA_TARGETS += littlewriter_target
```

**Comment by scottmc** [comment]
@bach5000 see if you can figure out how to fix the qmake file.

**Comment by scottmc** [comment]
@Giova84 can you add @owenca here as well?

**Comment by owenca** [comment]
@Giova84 From your README file I didn't see the qmake step before "make && addresource.sh." Did you have to run qmake outside of Haiku?

**Comment by Giova84** [comment]
The Makefile is already present (generated by qmake) in this repo, look at line 3: "Generated by qmake".

**Pull request merged**
