### PR TITLE
Add .rdef file

### PR DESCRIPTION
**Pull request by bach5000**
Here is the rdef file, but there are some problems that I've noticed...
* **addresource.sh:** `xres -o LittleWriter Littlewriter.rsrc`
This needs rsrc, so I guess if we convert the rsrc file to rdef file, we probably need to convert it back to rsrc, anyway.
* **Converting rdef back to rsrc:** used the command `rc Littlewriter.rsrc Littlewriter.rdef`
However, `rc` seems to be having trouble converting it back! Yields the error `rc: Error! Littlewriter.rdef:14 syntax error, unexpected TYPECODE`

Does anyone have any idea what's causing this error? The rdef file is included in this PR, so feel free to check line 14.

### CODE REVIEW

**Comment by owenca** [comment]
> * **addresource.sh:** `xres -o LittleWriter Littlewriter.rsrc`
>   This needs rsrc, so I guess if we convert the rsrc file to rdef file, we probably need to convert it back to rsrc, anyway.

See if you can convert the Makefile to use the Haiku makefile engine. Then you can add the rdef file to the new Makefile like you did with 256.

**Comment by bach5000** [comment]
@owenca How do you make Haiku's Makefile use qmake? Do I include qmake somewhere?

**Comment by bach5000** [comment]
@owenca I don't think I can do it without any examples of Haiku Makefiles using qmake. Can you provide links to some of the examples?

**Comment by owenca** [comment]
I think converting qmake to the Haiku Makefile Engine is beyond the task. Nevertheless, can you add to qmake a target that will compile the rdef file so that we don't need to keep the rsrc file and the shell script around? Maybe this [manual](https://doc.qt.io/archives/qt-4.8/qmake-manual.html) will help.

**Comment by owenca** [comment]
[This](https://doc.qt.io/qt-5/qmake-advanced-usage.html#adding-custom-targets) is more specific to what you might need.

**Comment by bach5000** [comment]
@Giova84 Sorry! The .rdef file isn't quite done yet...
Let me commit a bit more to that :)

**Comment by Giova84** [comment]
However: I invited owenca and Scott as collaborators of this repository, since they are more expert than me: guys, feel free to accept my request and to do what is better, please :-)

**Comment by Giova84** [comment]
Sorry: I am not very expert with Github, so: please make a new PR and I hope that owenca and Scott will take care of a better management :-)

**Pull request merged**
